### ISSUE TITLE
Error SignInWithApple.Authorize()

### ISSUE THREAD

**Issue by FelipeAhumada** [rlfrahm/capacitor-apple-login#2]
Hello, dear, I have the following problem. Install the package, I instantiate it, correctly as in the example code. But when I make the call it gives me an error.

`TypeError: undefined is not an object (evaluating 'SignInWithApple.Authorize')`

Attach configuration on my device. 
`
iphone 11: "appBuild":"1","osVersion":"13.4.1","operatingSystem":"ios"
Capacitor: 2.0.0
XCode 11 , Swift 5.1 
`

**Comment by ozonostudio** [comment]
I'm having the same exact issue

**Comment by mlynch** [comment]
Hi, see #3, but I just tested the forked version and I'm not getting this specific error: https://github.com/capacitor-community/apple-sign-in

**Comment by skibaalex** [comment]
@mlynch  @ozonostudio 
you need ionic cap sync after you install the plugin so it will be registered to capacitor/core plugins
